run-ubuntu:
	cd /tmp
	run-ubuntu
	cat /etc/debian_version
	cat /etc/os-release
	exit

run-debian:
	cd /tmp
	run-debian
	cat /etc/debian_version
	cat /etc/os-release
	exit

run-alpine:
	run-alpine /tmp
	cat /etc/alpine-release
	cat /etc/os-release
	exit

run-busybox:
	run-busybox /tmp
	ls /etc
	which busybox
	exit

run-fedora:
	cd /tmp
	run-fedora
	cat /etc/fedora-release
	cat /etc/os-release
	exit

run-almalinux:
	cd /tmp
	run-almalinux
	cat /etc/almalinux-release
	cat /etc/os-release
	exit

run-amazonlinux:
	run-amazonlinux /tmp
	cat /etc/amazon-linux-release
	cat /etc/os-release
	exit
