run-ubuntu:
	cd /tmp
	run-ubuntu
	cat /etc/debian_version
	cat /etc/os-release
	exit

run-debian:
	cd /tmp
	run-debian
	cat /etc/debian_version
	cat /etc/os-release
	exit

run-alpine:
	run-alpine /tmp
	cat /etc/alpine-release
	cat /etc/os-release
	exit
	